---
- name: Instala o Lamp nas maquinas
  hosts: web
  tasks:
  - name: Instala o apache nas maquinas
    dnf: name=httpd state=present

  - name: Inicia o apache
    service: name=httpd state=started
